/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/n3wscott/sources/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceSources implements ServiceSourceInterface
type FakeServiceSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var servicesourcesResource = schema.GroupVersionResource{Group: "sources.knative.dev", Version: "v1alpha1", Resource: "servicesources"}

var servicesourcesKind = schema.GroupVersionKind{Group: "sources.knative.dev", Version: "v1alpha1", Kind: "ServiceSource"}

// Get takes name of the serviceSource, and returns the corresponding serviceSource object, and an error if there is any.
func (c *FakeServiceSources) Get(name string, options v1.GetOptions) (result *v1alpha1.ServiceSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicesourcesResource, c.ns, name), &v1alpha1.ServiceSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceSource), err
}

// List takes label and field selectors, and returns the list of ServiceSources that match those selectors.
func (c *FakeServiceSources) List(opts v1.ListOptions) (result *v1alpha1.ServiceSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicesourcesResource, servicesourcesKind, c.ns, opts), &v1alpha1.ServiceSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceSourceList{ListMeta: obj.(*v1alpha1.ServiceSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServiceSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceSources.
func (c *FakeServiceSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicesourcesResource, c.ns, opts))

}

// Create takes the representation of a serviceSource and creates it.  Returns the server's representation of the serviceSource, and an error, if there is any.
func (c *FakeServiceSources) Create(serviceSource *v1alpha1.ServiceSource) (result *v1alpha1.ServiceSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicesourcesResource, c.ns, serviceSource), &v1alpha1.ServiceSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceSource), err
}

// Update takes the representation of a serviceSource and updates it. Returns the server's representation of the serviceSource, and an error, if there is any.
func (c *FakeServiceSources) Update(serviceSource *v1alpha1.ServiceSource) (result *v1alpha1.ServiceSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicesourcesResource, c.ns, serviceSource), &v1alpha1.ServiceSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceSources) UpdateStatus(serviceSource *v1alpha1.ServiceSource) (*v1alpha1.ServiceSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicesourcesResource, "status", c.ns, serviceSource), &v1alpha1.ServiceSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceSource), err
}

// Delete takes name of the serviceSource and deletes it. Returns an error if one occurs.
func (c *FakeServiceSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(servicesourcesResource, c.ns, name), &v1alpha1.ServiceSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicesourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceSourceList{})
	return err
}

// Patch applies the patch and returns the patched serviceSource.
func (c *FakeServiceSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicesourcesResource, c.ns, name, data, subresources...), &v1alpha1.ServiceSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceSource), err
}
