/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/n3wscott/sources/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJobSources implements JobSourceInterface
type FakeJobSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var jobsourcesResource = schema.GroupVersionResource{Group: "sources.knative.dev", Version: "v1alpha1", Resource: "jobsources"}

var jobsourcesKind = schema.GroupVersionKind{Group: "sources.knative.dev", Version: "v1alpha1", Kind: "JobSource"}

// Get takes name of the jobSource, and returns the corresponding jobSource object, and an error if there is any.
func (c *FakeJobSources) Get(name string, options v1.GetOptions) (result *v1alpha1.JobSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jobsourcesResource, c.ns, name), &v1alpha1.JobSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobSource), err
}

// List takes label and field selectors, and returns the list of JobSources that match those selectors.
func (c *FakeJobSources) List(opts v1.ListOptions) (result *v1alpha1.JobSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jobsourcesResource, jobsourcesKind, c.ns, opts), &v1alpha1.JobSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JobSourceList{ListMeta: obj.(*v1alpha1.JobSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.JobSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jobSources.
func (c *FakeJobSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jobsourcesResource, c.ns, opts))

}

// Create takes the representation of a jobSource and creates it.  Returns the server's representation of the jobSource, and an error, if there is any.
func (c *FakeJobSources) Create(jobSource *v1alpha1.JobSource) (result *v1alpha1.JobSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jobsourcesResource, c.ns, jobSource), &v1alpha1.JobSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobSource), err
}

// Update takes the representation of a jobSource and updates it. Returns the server's representation of the jobSource, and an error, if there is any.
func (c *FakeJobSources) Update(jobSource *v1alpha1.JobSource) (result *v1alpha1.JobSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jobsourcesResource, c.ns, jobSource), &v1alpha1.JobSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJobSources) UpdateStatus(jobSource *v1alpha1.JobSource) (*v1alpha1.JobSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jobsourcesResource, "status", c.ns, jobSource), &v1alpha1.JobSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobSource), err
}

// Delete takes name of the jobSource and deletes it. Returns an error if one occurs.
func (c *FakeJobSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(jobsourcesResource, c.ns, name), &v1alpha1.JobSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJobSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jobsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.JobSourceList{})
	return err
}

// Patch applies the patch and returns the patched jobSource.
func (c *FakeJobSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JobSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jobsourcesResource, c.ns, name, data, subresources...), &v1alpha1.JobSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JobSource), err
}
