apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: xkcd-sink
  labels:
    serving.knative.dev/visibility: "cluster-local"
spec:
  template:
    spec:
      containers:
      - image: github.com/n3wscott/sources/cmd/demos/xkcd-bot/cmd/bot
        env:
        - name: "GCHAT_WEBHOOK"
          valueFrom:
            secretKeyRef:
              name: "xkcd-secrets"
              key: "gchat-webhook"

