apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: xkcd-trigger
  namespace: default
spec:
  filter:
    attributes:
      type: xkcd.comic
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: xkcd-sink
