/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/n3wscott/sources/pkg/apis/sources/v1alpha1"
	scheme "github.com/n3wscott/sources/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JobSourcesGetter has a method to return a JobSourceInterface.
// A group's client should implement this interface.
type JobSourcesGetter interface {
	JobSources(namespace string) JobSourceInterface
}

// JobSourceInterface has methods to work with JobSource resources.
type JobSourceInterface interface {
	Create(*v1alpha1.JobSource) (*v1alpha1.JobSource, error)
	Update(*v1alpha1.JobSource) (*v1alpha1.JobSource, error)
	UpdateStatus(*v1alpha1.JobSource) (*v1alpha1.JobSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.JobSource, error)
	List(opts v1.ListOptions) (*v1alpha1.JobSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JobSource, err error)
	JobSourceExpansion
}

// jobSources implements JobSourceInterface
type jobSources struct {
	client rest.Interface
	ns     string
}

// newJobSources returns a JobSources
func newJobSources(c *SourcesV1alpha1Client, namespace string) *jobSources {
	return &jobSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jobSource, and returns the corresponding jobSource object, and an error if there is any.
func (c *jobSources) Get(name string, options v1.GetOptions) (result *v1alpha1.JobSource, err error) {
	result = &v1alpha1.JobSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JobSources that match those selectors.
func (c *jobSources) List(opts v1.ListOptions) (result *v1alpha1.JobSourceList, err error) {
	result = &v1alpha1.JobSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jobsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jobSources.
func (c *jobSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jobsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a jobSource and creates it.  Returns the server's representation of the jobSource, and an error, if there is any.
func (c *jobSources) Create(jobSource *v1alpha1.JobSource) (result *v1alpha1.JobSource, err error) {
	result = &v1alpha1.JobSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jobsources").
		Body(jobSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a jobSource and updates it. Returns the server's representation of the jobSource, and an error, if there is any.
func (c *jobSources) Update(jobSource *v1alpha1.JobSource) (result *v1alpha1.JobSource, err error) {
	result = &v1alpha1.JobSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobsources").
		Name(jobSource.Name).
		Body(jobSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *jobSources) UpdateStatus(jobSource *v1alpha1.JobSource) (result *v1alpha1.JobSource, err error) {
	result = &v1alpha1.JobSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jobsources").
		Name(jobSource.Name).
		SubResource("status").
		Body(jobSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the jobSource and deletes it. Returns an error if one occurs.
func (c *jobSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobsources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jobSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jobsources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched jobSource.
func (c *jobSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JobSource, err error) {
	result = &v1alpha1.JobSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jobsources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
