apiVersion: sources.knative.dev/v1alpha1
kind: JobSource
metadata:
  name: event-replay
  labels:
    controller-tools.k8s.io: "1.0"
spec:
  template:
    spec:
      containers:
      - name: event-replay
        image: github.com/n3wscott/sources/cmd/demos/event-replay
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: sockeye
