# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronjobsources.sources.knative.dev
  labels:
    sources.knative.dev/release: devel
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
spec:
  group: sources.knative.dev
  version: v1alpha1
  names:
    kind: CronJobSource
    plural: cronjobsources
    singular: cronjobsource
    categories:
    - all
    - knative
    shortNames:
    - cjs
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Schedule
    type: string
    JSONPath: ".spec.schedule"
  - name: Suspend
    type: boolean
    JSONPath: ".spec.suspend"
  - name: Active
    type: integer
    JSONPath: ".status.activeCount"
  - name: Last Schedule
    type: date
    JSONPath: ".status.lastScheduleTime"
  - name: Age
    type: date
    JSONPath: ".metadata.creationTimestamp"
  - name: Ready
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].status"
  - name: Reason
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].reason"
  - name: Message
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].message"
