apiVersion: sources.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: event-replay
spec:
  sink:
    # Change the kind and name for the sink as desired.
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: event-replay
            image: github.com/n3wscott/sources/cmd/demos/event-replay
            env:
              # FROM_COLLECTION defines the Firestore collection whose documents
              # will be replayed as events. Change this to the name of your
              # populated collection (if not using the default).
              - name: FROM_COLLECTION
                value: "purchases"
              # SINCE specifies we should replay all events since 20m ago.
              - name: SINCE
                value: "20m"
              # This is the environment variable that will hold the credentials for
              # Firestore. Make sure to upload your credentials as a secret through
              # Kubernetes.
              # Use the following command. "db-creds" and "db-svc-acct.json" can be
              # changed as long as they match the name and key fields below.
              # $ kubectl create secret generic db-creds --from-file=path/to/your/creds/db-svc-acct.json
              - name: GOOGLE_APPLICATION_CREDS_JSON
                valueFrom:
                  secretKeyRef:
                    name: db-creds
                    key: db-svc-acct.json
