apiVersion: sources.knative.dev/v1alpha1
kind: ServiceSource
metadata:
  name: forwarder
  description: forwarder forwards cloud events and other info posted to it
spec:
  template:
    spec:
      containers:
        - image: github.com/n3wscott/sources/cmd/demos/forwarder
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: sockeye
